### ISSUE TITLE
Add versi metadata 

### ISSUE THREAD

**Issue by bredamatt** [paritytech/polkadot-stps#57]
Versi metadata seems to be ahead of rococo metadata, so need to make sure there is a feature for that in `utils/src/lib.rs` 

- [x] Add Versi feature flag
- [x] Add Versi feature flag to Github action

**Comment by bernardoaraujor** [comment]
versi metadata should be extracted via:
```
subxt metadata --url <VERSI_URL> -f bytes > versi-meta.scale
```
